### ISSUE TITLE
'배달의 민족 기반' 명시

### ISSUE THREAD

**Issue by dhrgodms** [tipEthnic/tipEthnic#24]
홈페이지 상단에 배달의 민족 어플의 거리 측정 방식의 평균에 따라 계산됨을 명시

**Comment by dhrgodms** [comment]
거리 측정 방식의 "평균"이므로 100미터당 100원으로 설정함 또한 명시하도록 한다.

**Comment by Yoonseo1014** [comment]
1km당 100원으로 산정함을 명시하였다.
